import { defineObject, FieldType } from 'twenty-sdk/define';
import {
  DEAL_AMOUNT_FIELD_UID,
  DEAL_ARR_UID,
  DEAL_CLOSE_DATE_FIELD_UID,
  DEAL_CLOSED_LOST_REASON_UID,
  DEAL_CLOSED_WON_REASON_UID,
  DEAL_DESCRIPTION_FIELD_UID,
  DEAL_MRR_UID,
  DEAL_NAME_FIELD_UID,
  DEAL_NEXT_MEETING_NAME_UID,
  DEAL_NEXT_STEP_FIELD_UID,
  DEAL_PARTNER_TECH_WIN_UID,
  DEAL_PRIORITY_FIELD_UID,
  DEAL_PROBABILITY_UID,
  DEAL_SCORE_FIELD_UID,
  DEAL_STAGE_FIELD_UID,
  DEAL_TYPE_FIELD_UID,
  HS_PARTNER_DEAL_OBJECT_UID,
} from 'src/constants/universal-identifiers';

// Matches actual "Partner pipeline" in HubSpot (discovered 2026-06-05)
// HubSpot internal IDs → Twenty enum values (used in import.mjs mapping)
export const DEAL_STAGES = {
  APPOINTMENT_SCHEDULED: 'APPOINTMENT_SCHEDULED', // HS: appointmentscheduled
  QUALIFIED_TO_BUY: 'QUALIFIED_TO_BUY',           // HS: qualifiedtobuy
  PRESENTATION_SCHEDULED: 'PRESENTATION_SCHEDULED', // HS: presentationscheduled
  DECISION_MAKER_BOUGHT_IN: 'DECISION_MAKER_BOUGHT_IN', // HS: decisionmakerboughtin
  CONTRACT_SENT: 'CONTRACT_SENT',                 // HS: contractsent
  CLOSED_WON: 'CLOSED_WON',                       // HS: closedwon
  CLOSED_LOST: 'CLOSED_LOST',                     // HS: closedlost
  KEEP_WARM: 'KEEP_WARM',                         // HS: 1268133602
  DISQUALIFIED: 'DISQUALIFIED',                   // HS: 1277000404
} as const;

export default defineObject({
  universalIdentifier: HS_PARTNER_DEAL_OBJECT_UID,
  nameSingular: 'hsPartnerDeal',
  namePlural: 'hsPartnerDeals',
  labelSingular: 'Deal',
  labelPlural: 'Deals',
  description: 'Partner deal imported from HubSpot CRM',
  icon: 'IconCurrencyDollar',
  labelIdentifierFieldMetadataUniversalIdentifier: DEAL_NAME_FIELD_UID,
  fields: [
    {
      universalIdentifier: DEAL_NAME_FIELD_UID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Deal Name',
      description: 'Name of the deal',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: DEAL_AMOUNT_FIELD_UID,
      type: FieldType.CURRENCY,
      name: 'amount',
      label: 'Amount',
      description: 'Deal value',
      icon: 'IconCurrencyDollar',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DEAL_STAGE_FIELD_UID,
      type: FieldType.SELECT,
      name: 'stage',
      label: 'Stage',
      description: 'Current pipeline stage',
      icon: 'IconProgressCheck',
      defaultValue: `'${DEAL_STAGES.APPOINTMENT_SCHEDULED}'`,
      options: [
        {
          id: 'a1b2c3d4-0001-4e5f-8a9b-000000000001',
          value: DEAL_STAGES.APPOINTMENT_SCHEDULED,
          label: 'Reached out/Prospecting',
          position: 0,
          color: 'blue',
        },
        {
          id: 'a1b2c3d4-0002-4e5f-8a9b-000000000002',
          value: DEAL_STAGES.QUALIFIED_TO_BUY,
          label: 'Discovery Scheduled/Qualifying',
          position: 1,
          color: 'sky',
        },
        {
          id: 'a1b2c3d4-0003-4e5f-8a9b-000000000003',
          value: DEAL_STAGES.PRESENTATION_SCHEDULED,
          label: 'Pitch Scheduled/Aligning',
          position: 2,
          color: 'turquoise',
        },
        {
          id: 'a1b2c3d4-0004-4e5f-8a9b-000000000004',
          value: DEAL_STAGES.DECISION_MAKER_BOUGHT_IN,
          label: 'Verbal Agreement/Negotiation',
          position: 3,
          color: 'yellow',
        },
        {
          id: 'a1b2c3d4-0005-4e5f-8a9b-000000000005',
          value: DEAL_STAGES.CONTRACT_SENT,
          label: 'Contract Sent/Closing',
          position: 4,
          color: 'orange',
        },
        {
          id: 'a1b2c3d4-0006-4e5f-8a9b-000000000006',
          value: DEAL_STAGES.CLOSED_WON,
          label: 'Closed Won',
          position: 5,
          color: 'green',
        },
        {
          id: 'a1b2c3d4-0007-4e5f-8a9b-000000000007',
          value: DEAL_STAGES.CLOSED_LOST,
          label: 'Closed Lost',
          position: 6,
          color: 'red',
        },
        {
          id: 'a69c2101-8f7a-4574-92e9-c9629a7c6933',
          value: DEAL_STAGES.KEEP_WARM,
          label: 'Keep Warm',
          position: 7,
          color: 'sky',
        },
        {
          id: 'de5efdea-3768-4b32-a870-77a5c1ea3d63',
          value: DEAL_STAGES.DISQUALIFIED,
          label: 'Disqualified',
          position: 8,
          color: 'gray',
        },
      ],
    },
    {
      universalIdentifier: DEAL_CLOSE_DATE_FIELD_UID,
      type: FieldType.DATE,
      name: 'closeDate',
      label: 'Close Date',
      description: 'Expected or actual close date',
      icon: 'IconCalendar',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DEAL_TYPE_FIELD_UID,
      type: FieldType.SELECT,
      name: 'dealType',
      label: 'Deal Type',
      description: 'New business or existing business',
      icon: 'IconTag',
      isNullable: true,
      defaultValue: null,
      options: [
        {
          id: 'b2c3d4e5-0001-4f6a-9b0c-000000000001',
          value: 'NEW_BUSINESS',
          label: 'New Business',
          position: 0,
          color: 'purple',
        },
        {
          id: 'b2c3d4e5-0002-4f6a-9b0c-000000000002',
          value: 'EXISTING_BUSINESS',
          label: 'Existing Business',
          position: 1,
          color: 'gray',
        },
      ],
    },
    {
      universalIdentifier: DEAL_DESCRIPTION_FIELD_UID,
      type: FieldType.RICH_TEXT,
      name: 'description',
      label: 'Description',
      description: 'Deal notes and context',
      icon: 'IconNotes',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DEAL_NEXT_STEP_FIELD_UID,
      type: FieldType.TEXT,
      name: 'nextStep',
      label: 'Next Step',
      description: 'What the rep needs to do next (maps hs_next_step)',
      icon: 'IconArrowRight',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DEAL_PRIORITY_FIELD_UID,
      type: FieldType.SELECT,
      name: 'priority',
      label: 'Priority',
      description: 'Deal priority level (maps hs_priority)',
      icon: 'IconFlag',
      isNullable: true,
      defaultValue: null,
      options: [
        {
          id: 'ae31c8e5-1dc9-4769-9be3-35c2476275b9',
          value: 'HIGH',
          label: 'High',
          position: 0,
          color: 'red',
        },
        {
          id: '2c43be7e-b45e-4f78-b06b-435eeff5b668',
          value: 'MEDIUM',
          label: 'Medium',
          position: 1,
          color: 'yellow',
        },
        {
          id: 'c14faf6d-13c9-45c0-b349-4e3def51b720',
          value: 'LOW',
          label: 'Low',
          position: 2,
          color: 'gray',
        },
      ],
    },
    {
      universalIdentifier: DEAL_SCORE_FIELD_UID,
      type: FieldType.NUMBER,
      name: 'dealScore',
      label: 'Deal Score',
      description: 'HubSpot deal score (maps hs_deal_score)',
      icon: 'IconStar',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DEAL_PROBABILITY_UID,
      type: FieldType.NUMBER,
      name: 'dealProbability',
      label: 'Probability (%)',
      description: 'Deal close probability (maps hs_deal_stage_probability)',
      icon: 'IconChartBar',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DEAL_CLOSED_LOST_REASON_UID,
      type: FieldType.TEXT,
      name: 'closedLostReason',
      label: 'Closed Lost Reason',
      description: 'Why the deal was lost (maps closed_lost_reason)',
      icon: 'IconX',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DEAL_CLOSED_WON_REASON_UID,
      type: FieldType.TEXT,
      name: 'closedWonReason',
      label: 'Closed Won Reason',
      description: 'Why the deal was won (maps closed_won_reason)',
      icon: 'IconCheck',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DEAL_NEXT_MEETING_NAME_UID,
      type: FieldType.TEXT,
      name: 'nextMeetingName',
      label: 'Next Meeting',
      description: 'Name of next scheduled meeting (maps hs_next_meeting_name)',
      icon: 'IconCalendarEvent',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DEAL_PARTNER_TECH_WIN_UID,
      type: FieldType.SELECT,
      name: 'partnerTechWin',
      label: 'Partner Tech Win',
      description: 'Whether this is a partner tech win (maps hs_partner_tech_win)',
      icon: 'IconTrophy',
      isNullable: true,
      defaultValue: null,
      options: [
        { id: '7a8b9c0d-0001-4e5f-8a9b-700000000001', value: 'YES', label: 'Yes', position: 0, color: 'green' },
        { id: '7a8b9c0d-0002-4e5f-8a9b-700000000002', value: 'NO', label: 'No', position: 1, color: 'red' },
        { id: '7a8b9c0d-0003-4e5f-8a9b-700000000003', value: 'IN_PROGRESS', label: 'In Progress', position: 2, color: 'yellow' },
      ],
    },
    {
      universalIdentifier: DEAL_ARR_UID,
      type: FieldType.CURRENCY,
      name: 'arr',
      label: 'ARR',
      description: 'Annual recurring revenue (maps hs_arr)',
      icon: 'IconCurrencyDollar',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: DEAL_MRR_UID,
      type: FieldType.CURRENCY,
      name: 'mrr',
      label: 'MRR',
      description: 'Monthly recurring revenue (maps hs_mrr)',
      icon: 'IconCurrencyDollar',
      isNullable: true,
      defaultValue: null,
    },
  ],
});
