import { defineObject, FieldType } from 'twenty-sdk/define';
import { CALL_NAME_UID, CALL_OBJECT_UID } from 'src/constants/universal-identifiers';

// Phone calls logged from Dialpad (webhook: dialpad-events logic function).
// NOT the standard callRecording object — that one is meeting-bot lifecycle
// (calendar-event-bound); this is telephony: direction, outcome, duration.
export default defineObject({
  universalIdentifier: CALL_OBJECT_UID,
  nameSingular: 'call',
  namePlural: 'calls',
  labelSingular: 'Call',
  labelPlural: 'Calls',
  description: 'Dialpad phone calls — auto-logged by the dialpad-events webhook (sales department)',
  icon: 'IconPhone',
  labelIdentifierFieldMetadataUniversalIdentifier: CALL_NAME_UID,
  fields: [
  {
    universalIdentifier: CALL_NAME_UID,
    type: FieldType.TEXT,
    name: 'name',
    label: 'Name',
    description: 'Auto: "{Direction} call with {person} · {duration}"',
    icon: 'IconAbc',
  },
  {
    universalIdentifier: '8aa531da-380d-4874-98a2-c8eaac09c730',
    type: FieldType.SELECT,
    name: 'direction',
    label: 'Direction',
    description: 'Dialpad: direction',
    icon: 'IconArrowsLeftRight',
    options: [
      { id: 'faefc11b-915d-4a82-93c2-cd3d9e357302', value: 'INBOUND', label: 'Inbound', position: 0, color: 'blue' },
      { id: '55d74b14-0f1a-4b76-829b-0ae937ad4880', value: 'OUTBOUND', label: 'Outbound', position: 1, color: 'green' },
    ],
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '04139a1f-772d-487f-9516-dc47f2864505',
    type: FieldType.SELECT,
    name: 'outcome',
    label: 'Outcome',
    description: 'Derived from Dialpad call states — never downgraded on late/duplicate events',
    icon: 'IconPhoneCheck',
    options: [
      { id: '6d2f869e-b8d9-4c33-ab6a-93748e3f81db', value: 'COMPLETED', label: 'Completed', position: 0, color: 'green' },
      { id: 'e3789147-4ff1-4e2d-8e75-a7ef3647e923', value: 'MISSED', label: 'Missed', position: 1, color: 'red' },
      { id: '5f7c0592-afd8-4dca-ae74-0ce206749fa6', value: 'VOICEMAIL', label: 'Voicemail', position: 2, color: 'orange' },
      { id: '3b245660-eaa4-4236-8832-5d46a6515220', value: 'SMS', label: 'SMS', position: 3, color: 'purple' },
    ],
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: 'a95ccc1e-352a-4f18-afe3-70f86539a39b',
    type: FieldType.DATE_TIME,
    name: 'startedAt',
    label: 'Started At',
    description: 'Dialpad: date_started',
    icon: 'IconCalendarTime',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '77811008-8396-4aae-8f71-c57c6ccd1c90',
    type: FieldType.DATE_TIME,
    name: 'endedAt',
    label: 'Ended At',
    description: 'Dialpad: date_ended',
    icon: 'IconCalendarTime',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '39f6cba5-4f3e-4f95-9c2f-2599ee47ff36',
    type: FieldType.NUMBER,
    name: 'durationSeconds',
    label: 'Duration (s)',
    description: 'Dialpad: duration, talk time in seconds',
    icon: 'IconClock',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: 'ae24eb0f-2dfb-4cc7-af4c-3ce63c97de53',
    type: FieldType.TEXT,
    name: 'externalNumber',
    label: 'External Number',
    description: 'E.164 number of the external party (match key against person phones)',
    icon: 'IconPhone',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: 'd4915a63-ac0e-40ef-9cfc-835dc25cf0f4',
    type: FieldType.TEXT,
    name: 'dialpadUser',
    label: 'Dialpad User',
    description: 'FT person who handled the call (Dialpad target name/email)',
    icon: 'IconUserCircle',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: 'a81e1fcb-5c49-4e4e-a1e1-128a354d9181',
    type: FieldType.TEXT,
    name: 'dialpadCallId',
    // relabeled 2026-07-24: also stores Outreach call ids as `outreach-<id>` (EE-5069)
    label: 'External Call Id',
    description: 'Source-system call id — idempotency key (unique index; webhook retries upsert). Dialpad: raw call_id; Outreach: outreach-<id>',
    icon: 'IconKey',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: 'c12472ab-b804-4f98-985b-1cddfedb7a33',
    type: FieldType.SELECT,
    name: 'callSource',
    label: 'Call Source',
    description: 'System that logged this call (EE-5069)',
    icon: 'IconPlugConnected',
    isNullable: true,
    options: [
      { id: '35931d0b-085f-4e3d-a336-cf3573b7aa58', value: 'DIALPAD', label: 'Dialpad', position: 0, color: 'purple' },
      { id: '97e94401-c136-4d69-8d1e-8bf8887a78fc', value: 'OUTREACH', label: 'Outreach', position: 1, color: 'blue' },
    ],
    defaultValue: "'DIALPAD'",
  },
  {
    universalIdentifier: '668d912a-9830-4f1a-ba23-1307da1d0406',
    type: FieldType.LINKS,
    name: 'recordingUrl',
    label: 'Recording',
    description: 'Dialpad: recording_url (requires recordings_export scope)',
    icon: 'IconPlayerRecord',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: 'cea707d9-c767-4104-affe-dcc6c6258ed6',
    type: FieldType.LINKS,
    name: 'voicemailUrl',
    label: 'Voicemail',
    description: 'Dialpad: voicemail_link',
    icon: 'IconMailbox',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '5a08d246-8f90-4d3b-9752-245413e4d3e1',
    type: FieldType.TEXT,
    name: 'voicemailTranscript',
    label: 'Voicemail Transcript',
    description: 'Dialpad: transcription_text (voicemail only)',
    icon: 'IconFileText',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: 'cf7e12bd-6d76-4e4f-a71f-bd59eff4dedb',
    type: FieldType.TEXT,
    name: 'messageText',
    label: 'Message Text',
    description: 'SMS body (only when the Dialpad key has the Message content export scope)',
    icon: 'IconMessage',
    isNullable: true,
    defaultValue: null,
  },
  ],
});
