import { defineObject, FieldType } from 'twenty-sdk/define';

export default defineObject({
  universalIdentifier: 'bc651ce0-fff2-4a54-9196-03360d4a863c',
  nameSingular: 'termSheet',
  namePlural: 'termSheets',
  labelSingular: 'Term Sheet',
  labelPlural: 'Term Sheets',
  description: 'Client facility terms + fee-disclosure audit (source: Facility-Fee Audit sheet)',
  icon: 'IconFileDollar',
  labelIdentifierFieldMetadataUniversalIdentifier: 'c3aab0c0-da77-4090-8d9a-3a677000734e',
  fields: [
  {
    universalIdentifier: 'c3aab0c0-da77-4090-8d9a-3a677000734e',
    type: FieldType.TEXT,
    name: 'name',
    label: 'Name',
    description: 'Facility Terms — {Client}',
    icon: 'IconAbc',
  },
  {
    universalIdentifier: 'a9424593-33be-41d0-ae8e-7fd9b1c8ffda',
    type: FieldType.SELECT,
    name: 'status',
    label: "Status",
    description: "Imported: derived (SIGNED if source doc says SIGNED)",
    icon: 'IconList',
    options: [
      { id: 'b77f3c1b-1f55-4c38-aafe-ed6e24e963d2', value: 'DRAFT', label: "Draft", position: 0, color: 'blue' },
      { id: 'eea69dfc-73ff-419d-ba9e-f608781da40d', value: 'SENT', label: "Sent", position: 1, color: 'green' },
      { id: 'ae88f36d-7d51-4d89-8496-a786bcba955f', value: 'NEGOTIATING', label: "Negotiating", position: 2, color: 'turquoise' },
      { id: '8b7c529e-f63b-4f70-b534-7da159e5f198', value: 'SIGNED', label: "Signed", position: 3, color: 'yellow' },
      { id: 'f9895048-990a-4ccf-b72e-67c82b3e599c', value: 'EXPIRED', label: "Expired", position: 4, color: 'orange' },
      { id: 'd2970d96-c6da-451d-9061-063113893985', value: 'DECLINED', label: "Declined", position: 5, color: 'red' },
    ],
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: 'd9e2782b-9839-4d41-989d-9a58995fc8fe',
    type: FieldType.DATE,
    name: 'onboardDate',
    label: "Onboard Date",
    description: "Imported: audit col: Onboard date",
    icon: 'IconCalendar',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '95d4eccd-f972-436c-b32a-08e32f88c511',
    type: FieldType.TEXT,
    name: 'facilityFeeQuote',
    label: "Facility Fee Quote",
    description: "Imported: audit col: Exact quote disclosing the fee",
    icon: 'IconAbc',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '8a5ad97f-2907-454c-a249-da3bddfcf8a4',
    type: FieldType.SELECT,
    name: 'disclosureBucket',
    label: "Disclosure Bucket",
    description: "Imported: audit col: Disclosure bucket",
    icon: 'IconList',
    options: [
      { id: '27d04343-2c14-45b4-989f-6d7aba6aeb47', value: 'A_ONE_TIME_FEE_STATED', label: "A - One-time fee stated", position: 0, color: 'blue' },
      { id: '534f1830-c3fc-4e4b-bd6c-77e339879e43', value: 'B_FEE_MENTIONED_NO_CADENCE', label: "B - Fee mentioned no cadence", position: 1, color: 'green' },
      { id: '1e351897-41d6-46af-a4e0-c7101fa71bff', value: 'C_RECURRING', label: "C - Recurring", position: 2, color: 'turquoise' },
      { id: 'b799e3b1-f27b-4fa1-a451-4141d177940e', value: 'D_NO_DISCLOSURE', label: "D - No disclosure", position: 3, color: 'yellow' },
    ],
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '53a67427-27d1-4f26-b8cb-ef4bf3e9bf2b',
    type: FieldType.TEXT,
    name: 'disclosureSourceDoc',
    label: "Disclosure Source Doc",
    description: "Imported: audit col: Disclosure source doc",
    icon: 'IconAbc',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '5fa9992c-709c-4c02-9600-a65768a64444',
    type: FieldType.LINKS,
    name: 'documentLink',
    label: "Document Link",
    description: "Imported: audit col: Source link (Drive)",
    icon: 'IconLink',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '25aa631a-de4d-4674-adc9-5fe80f388d91',
    type: FieldType.CURRENCY,
    name: 'facilityFeeCharged',
    label: "Facility Fee Charged",
    description: "Imported: parsed from audit col: Facility fee charged (native ccy)",
    icon: 'IconCurrencyDollar',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '85e2d1f7-d2d6-4928-84c0-40baed6a50bd',
    type: FieldType.TEXT,
    name: 'facilityFeeChargedNote',
    label: "Facility Fee Charged Note",
    description: "Imported: audit col: Charged a facility fee? (raw)",
    icon: 'IconAbc',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '3915dfe1-134e-4507-bbfc-a07a47d24fbc',
    type: FieldType.SELECT,
    name: 'disclosureChargeMatch',
    label: "Disclosure Charge Match",
    description: "Imported: audit col: Disclosure-vs-charge match?",
    icon: 'IconList',
    options: [
      { id: 'f1f4a527-0d1d-4107-b667-a4f8997a783a', value: 'MATCH', label: "Match", position: 0, color: 'blue' },
      { id: '81d54e48-3e83-46b5-a22d-5911cf79726e', value: 'CONFLICT', label: "Conflict", position: 1, color: 'green' },
      { id: '700ba81f-516f-403d-b1ad-3bbcf8fee135', value: 'NONE', label: "None", position: 2, color: 'turquoise' },
    ],
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '9514452d-e8fb-4b25-8fb3-81853be1601e',
    type: FieldType.SELECT,
    name: 'auditConfidence',
    label: "Audit Confidence",
    description: "Imported: audit col: Confidence",
    icon: 'IconList',
    options: [
      { id: '7af595a5-2b6b-42bc-9c34-04f9c2649cfa', value: 'HIGH', label: "High", position: 0, color: 'blue' },
      { id: 'f9db3de9-adf2-44c6-b7e9-20b60a49ab66', value: 'MED', label: "Med", position: 1, color: 'green' },
      { id: 'd37a81d3-9ab2-4902-9001-f34dcb322553', value: 'LOW', label: "Low", position: 2, color: 'turquoise' },
    ],
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: 'c874e80b-f511-47b6-ad46-8038750888ec',
    type: FieldType.TEXT,
    name: 'minRequirement',
    label: "Min Requirement",
    description: "Imported: audit col: Min funding/balance requirement",
    icon: 'IconAbc',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '1fa425b7-741c-4f4b-a25d-6ed0211a95e0',
    type: FieldType.SELECT,
    name: 'minRequirementMet',
    label: "Min Requirement Met",
    description: "Imported: audit col: Met minimum requirement?",
    icon: 'IconList',
    options: [
      { id: '4d57cbe2-c3f9-4869-9d2e-d0b255a5ccb7', value: 'MET', label: "Met", position: 0, color: 'blue' },
      { id: '5742ed74-a18b-47e2-be30-7aec36e6130f', value: 'NOT_MET', label: "Not Met", position: 1, color: 'green' },
      { id: 'b344e8cb-4780-43dd-ac8f-28ccab35e637', value: 'REVIEW', label: "Review", position: 2, color: 'turquoise' },
      { id: '7432b91e-3ff9-4557-aebc-17096e5a529b', value: 'N_A', label: "N/A", position: 3, color: 'yellow' },
    ],
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: 'cf07be5f-9d12-4c96-91fc-aaa9ec410481',
    type: FieldType.RICH_TEXT,
    name: 'notes',
    label: "Notes",
    description: "Imported: audit col: Notes",
    icon: 'IconFileText',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '65bc1400-f429-4bcc-b7bf-5091dd0be349',
    type: FieldType.CURRENCY,
    name: 'creditLimit',
    label: "Credit Limit",
    description: "Imported: no source yet — doc-extracted later",
    icon: 'IconCurrencyDollar',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '5bfbea67-6cf3-4d36-b5a0-c3806f648576',
    type: FieldType.NUMBER,
    name: 'advanceRate',
    label: "Advance Rate",
    description: "Imported: no source yet — doc-extracted later",
    icon: 'IconNumber',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '91e4416a-425f-429e-bd76-bb50aa3e1709',
    type: FieldType.NUMBER,
    name: 'fundingFeeRate',
    label: "Funding Fee Rate",
    description: "Imported: no source yet — doc-extracted later",
    icon: 'IconNumber',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '32ac0a69-be92-4c41-8177-dbbe68f7f435',
    type: FieldType.NUMBER,
    name: 'transactionFeeRate',
    label: "Transaction Fee Rate",
    description: "Imported: no source yet — doc-extracted later",
    icon: 'IconNumber',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '5960958f-d810-4642-a871-092e0f90d1b8',
    type: FieldType.SELECT,
    name: 'termCurrency',
    label: "Term Currency",
    description: "Imported: no source yet — doc-extracted later",
    icon: 'IconList',
    options: [
      { id: 'a98bb6cb-3e2c-4901-818c-098716d0fa6e', value: 'CAD', label: "CAD", position: 0, color: 'blue' },
      { id: '77d92cd3-49cf-4a20-ac7b-081003c2521b', value: 'USD', label: "USD", position: 1, color: 'green' },
    ],
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: 'f2deca56-2816-4483-ba79-2ee62554c465',
    type: FieldType.NUMBER,
    name: 'termDays',
    label: "Term Days",
    description: "Imported: no source yet — doc-extracted later",
    icon: 'IconNumber',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '818db10e-4f05-4ab3-b8e7-4306e54bf286',
    type: FieldType.DATE,
    name: 'validUntil',
    label: "Valid Until",
    description: "Imported: no source yet — doc-extracted later",
    icon: 'IconCalendar',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '8b18869a-03e6-44ac-9b66-d3dd606a5b53',
    type: FieldType.DATE,
    name: 'sentAt',
    label: "Sent At",
    description: "Imported: no source yet — doc-extracted later",
    icon: 'IconCalendar',
    isNullable: true,
    defaultValue: null,
  },
  {
    universalIdentifier: '933d69d9-9b31-4b54-a0f3-609d527b1119',
    type: FieldType.DATE,
    name: 'signedAt',
    label: "Signed At",
    description: "Imported: no source yet — doc-extracted later",
    icon: 'IconCalendar',
    isNullable: true,
    defaultValue: null,
  },
  ],
});
